In [1]:

# dataframes - 2D 
import pandas as pd 

df= pd.DataFrame([12,13,22,21,10,7])
df

    0
0  12
1  13
2  22
3  21
4  10
5   7

In [2]:
df.shape

(6, 1)

In [3]:
df1= pd.DataFrame({'name':['Karan','Anmol','Aman','Nakul','Rohit','Mohit'],'class':['btech','bca','mba','mca','bca','btech'],'rollno':[12,11,14,10,5,8]})
df1

    name  class  rollno
0  Karan  btech      12
1  Anmol    bca      11
2   Aman    mba      14
3  Nakul    mca      10
4  Rohit    bca       5
5  Mohit  btech       8

In [4]:

df1.shape

(6, 3)

In [5]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   class   6 non-null      str
 2   rollno  6 non-null      int64
dtypes: int64(1), str(2)
memory usage: 327.0 bytes

In [6]:
df.columns

RangeIndex(start=0, stop=1, step=1)

In [7]:
#access - [], . , loc, iloc
df1['name']

0    Karan
1    Anmol
2     Aman
3    Nakul
4    Rohit
5    Mohit
Name: name, dtype: str

In [8]:
df1[:]

    name  class  rollno
0  Karan  btech      12
1  Anmol    bca      11
2   Aman    mba      14
3  Nakul    mca      10
4  Rohit    bca       5
5  Mohit  btech       8

In [9]:
df1[:2]

    name  class  rollno
0  Karan  btech      12
1  Anmol    bca      11

In [10]:
df1[1:6]

    name  class  rollno
1  Anmol    bca      11
2   Aman    mba      14
3  Nakul    mca      10
4  Rohit    bca       5
5  Mohit  btech       8

In [11]:
df1['name'][:3]

0    Karan
1    Anmol
2     Aman
Name: name, dtype: str

In [12]:
df1['class'][4]

'bca'

In [13]:
df1[['name','rollno']]

    name  rollno
0  Karan      12
1  Anmol      11
2   Aman      14
3  Nakul      10
4  Rohit       5
5  Mohit       8

In [14]:
#loc, iloc
df1.loc[:,:]# rows, columns

    name  class  rollno
0  Karan  btech      12
1  Anmol    bca      11
2   Aman    mba      14
3  Nakul    mca      10
4  Rohit    bca       5
5  Mohit  btech       8

In [15]:
df1.loc[:3,:]

    name  class  rollno
0  Karan  btech      12
1  Anmol    bca      11
2   Aman    mba      14
3  Nakul    mca      10

In [16]:
df1.iloc[:3,:]

    name  class  rollno
0  Karan  btech      12
1  Anmol    bca      11
2   Aman    mba      14

In [17]:
df1.loc[:,'name']

0    Karan
1    Anmol
2     Aman
3    Nakul
4    Rohit
5    Mohit
Name: name, dtype: str

In [18]:
df1.loc[:,['name','rollno']]

    name  rollno
0  Karan      12
1  Anmol      11
2   Aman      14
3  Nakul      10
4  Rohit       5
5  Mohit       8

In [19]:
df1.loc[2,'name']

'Aman'

In [20]:
df1.loc[2,:]

name      Aman
class      mba
rollno      14
Name: 2, dtype: object

In [21]:
#update rows and column and value
df1.loc[3,'class'] = 'bba'

In [22]:
df1

    name  class  rollno
0  Karan  btech      12
1  Anmol    bca      11
2   Aman    mba      14
3  Nakul    bba      10
4  Rohit    bca       5
5  Mohit  btech       8

In [23]:
df1.loc[:,'total_marks']= 40

In [24]:
df1

    name  class  rollno  total_marks
0  Karan  btech      12           40
1  Anmol    bca      11           40
2   Aman    mba      14           40
3  Nakul    bba      10           40
4  Rohit    bca       5           40
5  Mohit  btech       8           40

In [25]:
df1.loc[:,'marks'] = [32,35,29,28,37,38]

In [26]:
df1

    name  class  rollno  total_marks  marks
0  Karan  btech      12           40     32
1  Anmol    bca      11           40     35
2   Aman    mba      14           40     29
3  Nakul    bba      10           40     28
4  Rohit    bca       5           40     37
5  Mohit  btech       8           40     38

In [27]:
df1.insert(loc =3, column ='age',value = [23,24,22,21,25,19])

In [28]:
df1

    name  class  rollno  age  total_marks  marks
0  Karan  btech      12   23           40     32
1  Anmol    bca      11   24           40     35
2   Aman    mba      14   22           40     29
3  Nakul    bba      10   21           40     28
4  Rohit    bca       5   25           40     37
5  Mohit  btech       8   19           40     38

In [29]:
# rename column name 
df1.rename(columns={'class':'degree'},inplace=True)

In [30]:
df1

    name degree  rollno  age  total_marks  marks
0  Karan  btech      12   23           40     32
1  Anmol    bca      11   24           40     35
2   Aman    mba      14   22           40     29
3  Nakul    bba      10   21           40     28
4  Rohit    bca       5   25           40     37
5  Mohit  btech       8   19           40     38

In [34]:
df1.loc[:,'percentage']= (df1.loc[:,'marks']/df1.loc[:,'total_marks'])*100

In [35]:

# conditions 
df1[df1.loc[:,'degree']=='bca']

    name degree  rollno  age  total_marks  marks  percentage
1  Anmol    bca      11   24           40     35        87.5
4  Rohit    bca       5   25           40     37        92.5

In [36]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         6 non-null      str
 1   degree       6 non-null      str
 2   rollno       6 non-null      int64
 3   age          6 non-null      int64
 4   total_marks  6 non-null      int64
 5   marks        6 non-null      int64
 6   percentage   6 non-null      float64
dtypes: float64(1), int64(4), str(2)
memory usage: 519.0 bytes

In [37]:

df1.describe()

          rollno        age  total_marks      marks  percentage
count   6.000000   6.000000          6.0   6.000000    6.000000
mean   10.000000  22.333333         40.0  33.166667   82.916667
std     3.162278   2.160247          0.0   4.167333   10.418333
min     5.000000  19.000000         40.0  28.000000   70.000000
25%     8.500000  21.250000         40.0  29.750000   74.375000
50%    10.500000  22.500000         40.0  33.500000   83.750000
75%    11.750000  23.750000         40.0  36.500000   91.250000
max    14.000000  25.000000         40.0  38.000000   95.000000